[project]
name = "Truth-or-Lie-Market"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Truth-or-Lie-Market/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Truth-or-Lie-Market]
path = "contracts/Truth-or-Lie-Market.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
